### ISSUE TITLE
can not build ZCU104 Image

### ISSUE THREAD

**Issue by louisliuwei** [Xilinx/PYNQ#1123] opened 2020-09-08 03:18 UTC
Issue: an error will come up, cp: cannot stat '/group/bcapps/hqin/proj/pynq/PYNQ/boards/ZCU104/xilinx-zcu104-v2019.1-final.bsp': No such file or directory when building ZCU104 image
Resolution : need to remove "xilinx-zcu104-v2019.1-final.bsp" in /boards/ZCU104/ZCU104.spec

**Comment by giunatale** [comment] 2020-09-08 09:38
The ZCU104 board has an officially released bsp for Petalinux, that you can download here: https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/embedded-design-tools.html.

We rely on that for building the ZCU104 image. So what you are reporting is not a bug, but rather expected behavior. Closing

**Closed by giunatale** 2020-09-08 09:38 UTC
