### ISSUE TITLE
Activate Uart1

### ISSUE THREAD

**Issue by jihye0005** [Xilinx/PYNQ#785] opened 2019-01-14 01:50 UTC
Hi!

I am currently using the PYNQ-Z2 board, want to activate uart 1.
Cause I need two uarts, I need another one but uart0.

I created a bitstream in vivado, including uart1.
![image](https://user-images.githubusercontent.com/25446103/51093717-cf0c0100-17e9-11e9-8494-b8b72cecbfb5.png)

Then, what if I want to apply this bitstream to the board and use uart1?

Please let me know if there is a reference document or method.
Thank you!

**Comment by cathalmccabe** [comment] 2019-02-04 13:39
This is a duplicate of #794

**Closed** 2019-09-27 14:39 UTC
