### ISSUE TITLE
why dma xlnk in_buffer size limit to 4KB?

### ISSUE THREAD

**Issue by hisrg** [Xilinx/PYNQ#969] opened 2019-11-01 13:57 UTC
**For general questions, please use [the PYNQ discussion forum](https://discuss.
pynq.io/). We actively monitor the forum and try to answer every question 
there.**
my dma buffer size  wihout error is here: 
in_buffer = xlnk.cma_array(shape=(784), dtype=np.uint32)
out_buffer = xlnk.cma_array(shape=(784,), dtype=np.uint32)
,but when i change buffer size from 784 to 4095 as below code, it was error,
in_buffer = xlnk.cma_array(shape=(4095), dtype=np.uint32)
out_buffer = xlnk.cma_array(shape=(4095,), dtype=np.uint32),
why that?

Before submitting a pull request, you can also raise an issue that explains the 
problem the pull request is trying to resolve. Feel free to close the issue once
 the pull request has been merged.

If you still want to raise an issue here, please give us as much detail as 
possible to the issue you are seeing - we've listed some helpful fields below.

* PYNQ version (e.g. v2.5):
* Board name (e.g. Pynq-Z1):
* Pull request type (bug fix / new feature):
* Pull request number:
* Description:

**Comment by giunatale** [comment] 2019-11-01 14:13
The way you presented the issue is a bit confusing (also a bit hard to read). You should follow strictly the issue template.
Regardless, this sounds like a question to redirect on https://discuss.pynq.io.
Please post the question there and be a little more specific: what error you are getting, what are you trying to do exactly?

As many details as possible, otherwise it will difficult to provide effective advice.
I am closing this, please post your question on the dedicated [support forum]( https://discuss.pynq.io.). If from the conversation we find that this is a bug in our code, we'll open an issue here.

**Closed by giunatale** 2019-11-01 14:13 UTC
